version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel/collector.yml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP http receiver
      - "4317:4317" # OTLP grpc receiver

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"

  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/grafana/tempo.yml:/etc/tempo.yaml
      - ./tmp/tempo-data:/tmp/tempo
    ports:
      - "3200" # tempo
      - "4317"
